project:
  type: website 
  # 'render' controls what does and doesn't get rendered when i build (https://quarto.org/docs/websites/)
  render:
    - "*.qmd"
    # - "!posts/2021*/index.qmd"
    # - "!posts/2022*/index.qmd"
    - "!ignored.qmd"
    - "!ignored-dir/"

website:
  title: "Jacob Eliason"
  navbar:
    right:
      - blog.qmd 
      - text: Resume
        href: files/jacob-eliason-resume.pdf
      - icon: rss
        href: blog.xml
  favicon: files/favicon-sun.png
  site-url: "https://jacobeliason.com"
  google-analytics: "G-W5T2MB639Z"
  twitter-card: true # automatically generate a title, description, and preview image for the content when linked from Twitter
  open-graph: true
  comments:
    utterances:
      repo: jcblsn/jacobeliason.com
      label: comment
      issue-term: pathname
format:
  html:
    theme: 
      light: [sandstone-light, variables.scss]
    # header-includes: |
    #   <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/fira-sans" type="text/css"/>
    #   <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/fira-code" type="text/css"/>
    #   <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/roboto" type="text/css"/>
    # mainfont: RobotoRegular
    # monofont: FiraCodeRegular
    fontcolor: "black"
    linkcolor: "#ff1924"
    #"#7f7f7f"
    code-line-numbers: true
    code-copy: hover
    fig-responsive: true # ?
    search: false # excludes site from search engines
    # email-obfuscation: references
    # html-math-method: webtex
    css: styles.css
    include-in-header: 
      - text: |
          <script data-goatcounter="https://jacob.goatcounter.com/count" 
          async src="//gc.zgo.at/count.js"></script>
    execute:
      freeze: auto

editor: source