---
title: "On statistical pedagogy"
description: "Three observations at the conclusion of my master's program"
categories: [statistics]
author: "Jacob Eliason"
date: "2023-05-08"
draft: true
execute:
  freeze: auto  # re-render only when source changes
---

I completed a bachelor's degree in statistics in 2019 and am nearing the end of a master's degree in statistics this summer. Having now been a student of statistics in high school, university, and graduate school, this post is intended to clarify some of my thoughts about learning statistics. It could also be read as a letter of what I wish my first-year self could have known.

## Importance of mathematical foundation

Some people seem to promote statistics as a sort of alternative to math. 

- multivariate calculus and linear algebra as elective courses
- popular smart guy idea about replacing high school calculus with statistics

I don't believe this. I wish I would have committed to my relationship with calculus earlier.

- statistics made so much more sense after math 290

Consequences of statistics outside mathematics

- confusion about the central limit theorem and "large numbers of ns"
- nhst misery: ubiquitous inability to define p-values

## Critique of the 'Model Zoo' perspective

One consequence that deserves its own

- statistics as a basket of formulas or methods to be applied
- consider teaching everything using unified linear model-based approach

## Value of clearer boundaries between statistics and its disciplinary siblings

- Soft edges between statistics and other disciplines which use statistics
- A clear view of what statistics is for, as part of statistical literacy (description, inference, prediction)
- Differences between econometrics and statistics